# Generated by Django 4.0 on 2022-02-14 21:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaxisTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conn', models.JSONField(default=dict)),
                ('query', models.JSONField(default=dict)),
                ('result', models.TextField(blank=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('completedDT', models.DateTimeField(null=True)),
                ('progress', models.TextField()),
                ('owner', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['createdDT'],
            },
        ),
    ]
