# Generated by Django 4.0 on 2022-02-16 13:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PlaxisTask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaxisDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='plaxis/documents/%Y/%m/%d')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskfiles', to='PlaxisTask.plaxistask')),
            ],
        ),
    ]
