# Generated by Django 4.0 on 2022-02-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaxisTask', '0002_plaxisdocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaxisdocuments',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/plaxis/documents/%Y/%m/%d'),
        ),
    ]
