# Generated by Django 4.0 on 2022-02-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaxisTask', '0003_alter_plaxisdocuments_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaxisdocuments',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='plaxis/documents/%Y/%m/%d'),
        ),
    ]
